config = {
    "smart_device_readings": {
        "partition_cols": ["date"],
        "table_schema": {
            # Meta Data
            "date_extracted": {"type": "date", "comment": "Date of when the ETL ran"},
            "timestamp_extracted": {"type": "timestamp", "comment": "Timestamp of when the ETL ran"},
            "timestamp": {"type": "timestamp", "comment": "From the record. Units: s"},
            "date": {"type": "date", "comment": "date from record"},
            # Gateway Data
            "gateway_name": {"comment": "_", "type": "string"},
            "gateway_model": {"comment": "_", "type": "string"},
            "gateway_serial": {"comment": "_", "type": "string"},
            # Device Data
            "device_name": {"comment": "_", "type": "string"},
            "device_model": {"comment": "_", "type": "string"},
            "device_serial": {"comment": "_", "type": "string"},
            "device_online": {"comment": "_", "type": "boolean"},
            # Readings
            "line_to_neutral_voltage_phase_a": {"comment": "Units: V", "type": "float"},
            "line_to_neutral_voltage_phase_b": {"comment": "Units: V", "type": "float"},
            "line_to_neutral_voltage_phase_c": {"comment": "Units: V", "type": "float"},
            "line_to_neutral_voltage_average": {"comment": "Units: V", "type": "float"},
            "line_to_line_voltage_line_ab": {"comment": "Units: V", "type": "float"},
            "line_to_line_voltage_line_bc": {"comment": "Units: V", "type": "float"},
            "line_to_line_voltage_line_ca": {"comment": "Units: V", "type": "float"},
            "line_to_line_voltage_average": {"comment": "Units: V", "type": "float"},
            "line_current_overall_phase_a": {"comment": "Units: A", "type": "float"},
            "line_current_overall_phase_b": {"comment": "Units: A", "type": "float"},
            "line_current_overall_phase_c": {"comment": "Units: A", "type": "float"},
            "line_current_overall_average": {"comment": "Units: A", "type": "float"},
            "line_current_overall_neutral": {"comment": "Units: A", "type": "float"},
            "line_current_source_1_phase_a": {"comment": "Units: A", "type": "float"},
            "line_current_source_1_phase_b": {"comment": "Units: A", "type": "float"},
            "line_current_source_1_phase_c": {"comment": "Units: A", "type": "float"},
            "line_current_source_2_phase_a": {"comment": "Units: A", "type": "float"},
            "line_current_source_2_phase_b": {"comment": "Units: A", "type": "float"},
            "line_current_source_2_phase_c": {"comment": "Units: A", "type": "float"},
            "line_current_source_3_phase_a": {"comment": "Units: A", "type": "float"},
            "line_current_source_3_phase_b": {"comment": "Units: A", "type": "float"},
            "line_current_source_3_phase_c": {"comment": "Units: A", "type": "float"},
            "line_current_source_4_phase_a": {"comment": "Units: A", "type": "float"},
            "line_current_source_4_phase_b": {"comment": "Units: A", "type": "float"},
            "line_current_source_4_phase_c": {"comment": "Units: A", "type": "float"},
            "line_current_source_5_phase_a": {"comment": "Units: A", "type": "float"},
            "line_current_source_5_phase_b": {"comment": "Units: A", "type": "float"},
            "line_current_source_5_phase_c": {"comment": "Units: A", "type": "float"},
            "line_current_source_6_phase_a": {"comment": "Units: A", "type": "float"},
            "line_current_source_6_phase_b": {"comment": "Units: A", "type": "float"},
            "line_current_source_6_phase_c": {"comment": "Units: A", "type": "float"},
            "active_power_overall_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_overall_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_overall_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_overall_total": {"comment": "Units: kW", "type": "float"},
            "active_power_source_1_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_source_1_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_source_1_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_source_2_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_source_2_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_source_2_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_source_3_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_source_3_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_source_3_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_source_4_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_source_4_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_source_4_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_source_5_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_source_5_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_source_5_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_source_6_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_source_6_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_source_6_phase_c": {"comment": "Units: kW", "type": "float"},
            "reactive_power_overall_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_overall_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_overall_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_overall_average": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_1_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_1_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_1_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_2_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_2_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_2_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_3_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_3_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_3_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_4_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_4_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_4_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_5_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_5_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_5_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_6_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_6_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_source_6_phase_c": {"comment": "Units: kvar", "type": "float"},
            "apparent_power_overall_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_overall_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_overall_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_overall_total": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_1_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_1_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_1_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_2_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_2_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_2_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_3_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_3_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_3_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_4_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_4_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_4_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_5_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_5_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_5_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_6_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_6_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_source_6_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_overall_average": {"comment": "Units: kVA", "type": "float"},
            "power_factor_overall_phase_a": {"comment": "Units: kW", "type": "float"},
            "power_factor_overall_phase_b": {"comment": "Units: kW", "type": "float"},
            "power_factor_overall_phase_c": {"comment": "Units: kW", "type": "float"},
            "power_factor_overall": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_1_phase_a": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_1_phase_b": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_1_phase_c": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_2_phase_a": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_2_phase_b": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_2_phase_c": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_3_phase_a": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_3_phase_b": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_3_phase_c": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_4_phase_a": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_4_phase_b": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_4_phase_c": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_5_phase_a": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_5_phase_b": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_5_phase_c": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_6_phase_a": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_6_phase_b": {"comment": "Units: kW", "type": "float"},
            "power_factor_source_6_phase_c": {"comment": "Units: kW", "type": "float"},
            "frequency": {"comment": "Units: Hz", "type": "float"},
            "load_type": {"comment": "Units: None", "type": "string"},
            "import_active_energy_overall_phase_a": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_overall_phase_b": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_overall_phase_c": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_overall_total": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_1_phase_a": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_1_phase_b": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_1_phase_c": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_2_phase_a": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_2_phase_b": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_2_phase_c": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_3_phase_a": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_3_phase_b": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_3_phase_c": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_4_phase_a": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_4_phase_b": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_4_phase_c": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_5_phase_a": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_5_phase_b": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_5_phase_c": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_6_phase_a": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_6_phase_b": {"comment": "Units: kWh", "type": "float"},
            "import_active_energy_source_6_phase_c": {"comment": "Units: kWh", "type": "float"},
            "import_reactive_energy_overall_phase_a": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_overall_phase_b": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_overall_phase_c": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_overall_total": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_1_phase_a": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_1_phase_b": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_1_phase_c": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_2_phase_a": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_2_phase_b": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_2_phase_c": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_3_phase_a": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_3_phase_b": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_3_phase_c": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_4_phase_a": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_4_phase_b": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_4_phase_c": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_5_phase_a": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_5_phase_b": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_5_phase_c": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_6_phase_a": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_6_phase_b": {"comment": "Units: kvarh", "type": "float"},
            "import_reactive_energy_source_6_phase_c": {"comment": "Units: kvarh", "type": "float"},
            "apparent_energy_overall_phase_a": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_overall_phase_b": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_overall_phase_c": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_overall_total": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_1_phase_a": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_1_phase_b": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_1_phase_c": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_2_phase_a": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_2_phase_b": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_2_phase_c": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_3_phase_a": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_3_phase_b": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_3_phase_c": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_4_phase_a": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_4_phase_b": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_4_phase_c": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_5_phase_a": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_5_phase_b": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_5_phase_c": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_6_phase_a": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_6_phase_b": {"comment": "Units: kvAh", "type": "float"},
            "apparent_energy_source_6_phase_c": {"comment": "Units: kvAh", "type": "float"},
            "active_power_demand_overall_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_overall_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_overall_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_overall_total": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_1_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_1_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_1_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_2_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_2_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_2_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_3_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_3_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_3_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_4_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_4_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_4_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_5_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_5_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_5_phase_c": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_6_phase_a": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_6_phase_b": {"comment": "Units: kW", "type": "float"},
            "active_power_demand_source_6_phase_c": {"comment": "Units: kW", "type": "float"},
            "reactive_power_demand_overall_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_overall_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_overall_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_overall_total": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_1_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_1_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_1_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_2_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_2_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_2_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_3_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_3_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_3_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_4_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_4_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_4_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_5_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_5_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_5_phase_c": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_6_phase_a": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_6_phase_b": {"comment": "Units: kvar", "type": "float"},
            "reactive_power_demand_source_6_phase_c": {"comment": "Units: kvar", "type": "float"},
            "apparent_power_demand_overall_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_overall_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_overall_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_overall_total": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_1_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_1_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_1_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_2_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_2_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_2_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_3_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_3_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_3_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_4_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_4_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_4_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_5_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_5_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_5_phase_c": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_6_phase_a": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_6_phase_b": {"comment": "Units: kVA", "type": "float"},
            "apparent_power_demand_source_6_phase_c": {"comment": "Units: kVA", "type": "float"},
            "current_demand_overall_phase_a": {"comment": "Units: A", "type": "float"},
            "current_demand_overall_phase_b": {"comment": "Units: A", "type": "float"},
            "current_demand_overall_phase_c": {"comment": "Units: A", "type": "float"},
            "current_demand_source_1_phase_a": {"comment": "Units: A", "type": "float"},
            "current_demand_source_1_phase_b": {"comment": "Units: A", "type": "float"},
            "current_demand_source_1_phase_c": {"comment": "Units: A", "type": "float"},
            "current_demand_source_2_phase_a": {"comment": "Units: A", "type": "float"},
            "current_demand_source_2_phase_b": {"comment": "Units: A", "type": "float"},
            "current_demand_source_2_phase_c": {"comment": "Units: A", "type": "float"},
            "current_demand_source_3_phase_a": {"comment": "Units: A", "type": "float"},
            "current_demand_source_3_phase_b": {"comment": "Units: A", "type": "float"},
            "current_demand_source_3_phase_c": {"comment": "Units: A", "type": "float"},
            "current_demand_source_4_phase_a": {"comment": "Units: A", "type": "float"},
            "current_demand_source_4_phase_b": {"comment": "Units: A", "type": "float"},
            "current_demand_source_4_phase_c": {"comment": "Units: A", "type": "float"},
            "current_demand_source_5_phase_a": {"comment": "Units: A", "type": "float"},
            "current_demand_source_5_phase_b": {"comment": "Units: A", "type": "float"},
            "current_demand_source_5_phase_c": {"comment": "Units: A", "type": "float"},
            "current_demand_source_6_phase_a": {"comment": "Units: A", "type": "float"},
            "current_demand_source_6_phase_b": {"comment": "Units: A", "type": "float"},
            "current_demand_source_6_phase_c": {"comment": "Units: A", "type": "float"},
            "voltage_unbalance_factor": {"comment": "Units: %", "type": "float"},
            "current_unbalance_factor": {"comment": "Units: %", "type": "float"},
            "voltage_crest_factor_overall_phase_a": {"comment": "Units: %", "type": "float"},
            "voltage_crest_factor_overall_phase_b": {"comment": "Units: %", "type": "float"},
            "voltage_crest_factor_overall_phase_c": {"comment": "Units: %", "type": "float"},
            "current_k_factor_overall_phase_a": {"comment": "Units: %", "type": "float"},
            "current_k_factor_overall_phase_b": {"comment": "Units: %", "type": "float"},
            "current_k_factor_overall_phase_c": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_1_phase_a": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_1_phase_b": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_1_phase_c": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_2_phase_a": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_2_phase_b": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_2_phase_c": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_3_phase_a": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_3_phase_b": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_3_phase_c": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_4_phase_a": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_4_phase_b": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_4_phase_c": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_5_phase_a": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_5_phase_b": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_5_phase_c": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_6_phase_a": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_6_phase_b": {"comment": "Units: %", "type": "float"},
            "current_k_factor_source_6_phase_c": {"comment": "Units: %", "type": "float"},
            "di_counter_channel_1": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_2": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_3": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_4": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_5": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_6": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_7": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_8": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_9": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_10": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_11": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_12": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_13": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_14": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_15": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_16": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_17": {"comment": "Units: None", "type": "float"},
            "di_counter_channel_18": {"comment": "Units: None", "type": "float"},
            "analog_input_channel_1": {"comment": "Units: None", "type": "float"},
            "analog_input_channel_2": {"comment": "Units: None", "type": "float"},
            "analog_input_channel_3": {"comment": "Units: None", "type": "float"},
            "analog_input_channel_4": {"comment": "Units: None", "type": "float"},
        },
        "format_types": {
            "acuvim-ii": {
                "unique_features": {"num_columns": 209, "has_columns": ["timestamp", "gateway_name", "device_name"]},
                "map": {
                    # Meta Data
                    "timestamp": {"comment": "From the record. Units: ms", "unit": "s", "target_column": "timestamp"},
                    # Gateway Data
                    "gateway_name": {"comment": "_", "target_column": "gateway_name"},
                    "gateway_model": {"comment": "_", "target_column": "gateway_model"},
                    "gateway_serial": {"comment": "_", "target_column": "gateway_serial"},
                    # Device Data
                    "device_name": {"comment": "_", "target_column": "device_name"},
                    "device_model": {"comment": "_", "target_column": "device_model"},
                    "device_serial": {"comment": "_", "target_column": "device_serial"},
                    "device_online": {"comment": "_", "target_column": "device_online"},
                    # Record Data
                    "device_readings_0_value": {
                        "comment": "Units: V",
                        "target_column": "line_to_neutral_voltage_phase_a",
                    },
                    "device_readings_1_value": {
                        "comment": "Units: V",
                        "target_column": "line_to_neutral_voltage_phase_b",
                    },
                    "device_readings_2_value": {
                        "comment": "Units: V",
                        "target_column": "line_to_neutral_voltage_phase_c",
                    },
                    "device_readings_3_value": {
                        "comment": "Units: V",
                        "target_column": "line_to_neutral_voltage_average",
                    },
                    "device_readings_4_value": {"comment": "Units: V", "target_column": "line_to_line_voltage_line_ab"},
                    "device_readings_5_value": {"comment": "Units: V", "target_column": "line_to_line_voltage_line_bc"},
                    "device_readings_6_value": {"comment": "Units: V", "target_column": "line_to_line_voltage_line_ca"},
                    "device_readings_7_value": {"comment": "Units: V", "target_column": "line_to_line_voltage_average"},
                    "device_readings_8_value": {"comment": "Units: A", "target_column": "line_current_overall_phase_a"},
                    "device_readings_9_value": {"comment": "Units: A", "target_column": "line_current_overall_phase_b"},
                    "device_readings_10_value": {
                        "comment": "Units: A",
                        "target_column": "line_current_overall_phase_c",
                    },
                    "device_readings_11_value": {
                        "comment": "Units: A",
                        "target_column": "line_current_overall_average",
                    },
                    "device_readings_12_value": {
                        "comment": "Units: A",
                        "target_column": "line_current_overall_neutral",
                    },
                    "device_readings_13_value": {
                        "comment": "Units: kW",
                        "target_column": "active_power_overall_phase_a",
                    },
                    "device_readings_14_value": {
                        "comment": "Units: kW",
                        "target_column": "active_power_overall_phase_b",
                    },
                    "device_readings_15_value": {
                        "comment": "Units: kW",
                        "target_column": "active_power_overall_phase_c",
                    },
                    "device_readings_16_value": {"comment": "Units: kW", "target_column": "active_power_overall_total"},
                    "device_readings_17_value": {
                        "comment": "Units: kvar",
                        "target_column": "reactive_power_overall_phase_a",
                    },
                    "device_readings_18_value": {
                        "comment": "Units: kvar",
                        "target_column": "reactive_power_overall_phase_b",
                    },
                    "device_readings_19_value": {
                        "comment": "Units: kvar",
                        "target_column": "reactive_power_overall_phase_c",
                    },
                    "device_readings_20_value": {
                        "comment": "Units: kvar",
                        "target_column": "reactive_power_overall_average",
                    },
                    "device_readings_21_value": {
                        "comment": "Units: kVA",
                        "target_column": "apparent_power_overall_phase_a",
                    },
                    "device_readings_22_value": {
                        "comment": "Units: kVA",
                        "target_column": "apparent_power_overall_phase_b",
                    },
                    "device_readings_23_value": {
                        "comment": "Units: kVA",
                        "target_column": "apparent_power_overall_phase_c",
                    },
                    "device_readings_24_value": {
                        "comment": "Units: kVA",
                        "target_column": "apparent_power_overall_total",
                    },
                    "device_readings_25_value": {
                        "comment": "Units: None",
                        "target_column": "power_factor_overall_phase_a",
                    },
                    "device_readings_26_value": {
                        "comment": "Units: None",
                        "target_column": "power_factor_overall_phase_b",
                    },
                    "device_readings_27_value": {
                        "comment": "Units: None",
                        "target_column": "power_factor_overall_phase_c",
                    },
                    "device_readings_28_value": {"comment": "Units: None", "target_column": "power_factor_overall"},
                    "device_readings_29_value": {"comment": "Units: Hz", "target_column": "frequency"},
                    "device_readings_30_value": {
                        "comment": "Units: None",
                        "type": "string",
                        "comment": "Units: None",
                        "target_column": "load_type",
                    },
                    "device_readings_31_value": {
                        "comment": "Units: kWh",
                        "target_column": "import_active_energy_overall_phase_a",
                    },
                    "device_readings_32_value": {
                        "comment": "Units: kWh",
                        "target_column": "import_active_energy_overall_phase_b",
                    },
                    "device_readings_33_value": {
                        "comment": "Units: kWh",
                        "target_column": "import_active_energy_overall_phase_c",
                    },
                    "device_readings_34_value": {
                        "comment": "Units: kWh",
                        "target_column": "import_active_energy_overall_total",
                    },
                    "device_readings_35_value": {
                        "comment": "Units: kvarh",
                        "target_column": "import_reactive_energy_overall_phase_a",
                    },
                    "device_readings_36_value": {
                        "comment": "Units: kvarh",
                        "target_column": "import_reactive_energy_overall_phase_b",
                    },
                    "device_readings_37_value": {
                        "comment": "Units: kvarh",
                        "target_column": "import_reactive_energy_overall_phase_c",
                    },
                    "device_readings_38_value": {
                        "comment": "Units: kvarh",
                        "target_column": "import_reactive_energy_overall_total",
                    },
                    "device_readings_39_value": {
                        "comment": "Units: kvAh",
                        "target_column": "apparent_energy_overall_phase_a",
                    },
                    "device_readings_40_value": {
                        "comment": "Units: kvAh",
                        "target_column": "apparent_energy_overall_phase_b",
                    },
                    "device_readings_41_value": {
                        "comment": "Units: kvAh",
                        "target_column": "apparent_energy_overall_phase_c",
                    },
                    "device_readings_42_value": {
                        "comment": "Units: kvAh",
                        "target_column": "apparent_energy_overall_total",
                    },
                    "device_readings_43_value": {
                        "comment": "Units: kW",
                        "target_column": "active_power_demand_overall_total",
                    },
                    "device_readings_44_valuer": {
                        "comment": "Units: kvar",
                        "target_column": "reactive_power_demand_overall_total",
                    },
                    "device_readings_45_value": {
                        "comment": "Units: kVA",
                        "target_column": "apparent_power_demand_overall_total",
                    },
                    "device_readings_46_value": {
                        "comment": "Units: A",
                        "target_column": "current_demand_overall_phase_a",
                    },
                    "device_readings_47_value": {
                        "comment": "Units: A",
                        "target_column": "current_demand_overall_phase_b",
                    },
                    "device_readings_48_value": {
                        "comment": "Units: A",
                        "target_column": "current_demand_overall_phase_c",
                    },
                    "device_readings_49_value": {"comment": "Units: %", "target_column": "voltage_unbalance_factor"},
                    "device_readings_50_value": {"comment": "Units: %", "target_column": "current_unbalance_factor"},
                    "device_readings_51_value": {
                        "comment": "Units: %",
                        "target_column": "voltage_crest_factor_overall_phase_a",
                    },
                    "device_readings_52_value": {
                        "comment": "Units: %",
                        "target_column": "voltage_crest_factor_overall_phase_b",
                    },
                    "device_readings_53_value": {
                        "comment": "Units: %",
                        "target_column": "voltage_crest_factor_overall_phase_c",
                    },
                    "device_readings_54_value": {
                        "comment": "Units: %",
                        "target_column": "current_k_factor_overall_phase_a",
                    },
                    "device_readings_55_value": {
                        "comment": "Units: %",
                        "target_column": "current_k_factor_overall_phase_b",
                    },
                    "device_readings_56_value": {
                        "comment": "Units: %",
                        "target_column": "current_k_factor_overall_phase_c",
                    },
                    "device_readings_57_value": {"comment": "Units: None", "target_column": "di_counter_channel_1"},
                    "device_readings_58_value": {"comment": "Units: None", "target_column": "di_counter_channel_2"},
                    "device_readings_59_value": {"comment": "Units: None", "target_column": "di_counter_channel_3"},
                    "device_readings_60_value": {"comment": "Units: None", "target_column": "di_counter_channel_4"},
                    "device_readings_61_value": {"comment": "Units: None", "target_column": "di_counter_channel_5"},
                    "device_readings_62_value": {"comment": "Units: None", "target_column": "di_counter_channel_6"},
                    "device_readings_63_value": {"comment": "Units: None", "target_column": "analog_input_channel_1"},
                    "device_readings_64_value": {"comment": "Units: None", "target_column": "analog_input_channel_2"},
                    "device_readings_65_value": {"comment": "Units: None", "target_column": "analog_input_channel_3"},
                    "device_readings_66_value": {"comment": "Units: None", "target_column": "analog_input_channel_4"},
                },
            },
            "acurev-2100": {
                "unique_features": {"num_columns": 1446, "has_columns": ["deviceId", "metrics_1_value"]},
                "map": {
                    "deviceId": {"target_column": "gateway_serial"},
                    "metrics_0_timestamp": {"target_column": "timestamp", "unit": "ISO_OFFSET_DATE_TIME"},
                    "device_model": {"target_column": "device_model", "default": "Acurev-2100"},
                    "metrics_0_value": {"target_column": "line_to_neutral_voltage_phase_a"},
                    "metrics_1_value": {"target_column": "line_to_neutral_voltage_phase_b"},
                    "metrics_2_value": {"target_column": "line_to_neutral_voltage_phase_c"},
                    "metrics_3_value": {"target_column": "line_to_neutral_voltage_average"},
                    "metrics_4_value": {"target_column": "line_to_line_voltage_line_ab"},
                    "metrics_5_value": {"target_column": "line_to_line_voltage_line_bc"},
                    "metrics_6_value": {"target_column": "line_to_line_voltage_line_ca"},
                    "metrics_7_value": {"target_column": "line_to_line_voltage_average"},
                    "metrics_8_value": {"target_column": "line_current_overall_phase_a"},
                    "metrics_9_value": {"target_column": "line_current_overall_phase_b"},
                    "metrics_10_value": {"target_column": "line_current_overall_phase_c"},
                    "metrics_29_value": {"target_column": "line_current_overall_average"},
                    "metrics_11_value": {"target_column": "line_current_source_1_phase_a"},
                    "metrics_12_value": {"target_column": "line_current_source_1_phase_b"},
                    "metrics_13_value": {"target_column": "line_current_source_1_phase_c"},
                    "metrics_14_value": {"target_column": "line_current_source_2_phase_a"},
                    "metrics_15_value": {"target_column": "line_current_source_2_phase_b"},
                    "metrics_16_value": {"target_column": "line_current_source_2_phase_c"},
                    "metrics_17_value": {"target_column": "line_current_source_3_phase_a"},
                    "metrics_18_value": {"target_column": "line_current_source_3_phase_b"},
                    "metrics_19_value": {"target_column": "line_current_source_3_phase_c"},
                    "metrics_20_value": {"target_column": "line_current_source_4_phase_a"},
                    "metrics_21_value": {"target_column": "line_current_source_4_phase_b"},
                    "metrics_22_value": {"target_column": "line_current_source_4_phase_c"},
                    "metrics_23_value": {"target_column": "line_current_source_5_phase_a"},
                    "metrics_24_value": {"target_column": "line_current_source_5_phase_b"},
                    "metrics_25_value": {"target_column": "line_current_source_5_phase_c"},
                    "metrics_26_value": {"target_column": "line_current_source_6_phase_a"},
                    "metrics_27_value": {"target_column": "line_current_source_6_phase_b"},
                    "metrics_28_value": {"target_column": "line_current_source_6_phase_c"},
                    "metrics_30_value": {"target_column": "active_power_overall_phase_a"},
                    "metrics_31_value": {"target_column": "active_power_overall_phase_b"},
                    "metrics_32_value": {"target_column": "active_power_overall_phase_c"},
                    "metrics_57_value": {"target_column": "active_power_overall_total"},
                    "metrics_33_value": {"target_column": "active_power_source_1_phase_a"},
                    "metrics_34_value": {"target_column": "active_power_source_1_phase_b"},
                    "metrics_35_value": {"target_column": "active_power_source_1_phase_c"},
                    "metrics_36_value": {"target_column": "active_power_source_2_phase_a"},
                    "metrics_37_value": {"target_column": "active_power_source_2_phase_b"},
                    "metrics_38_value": {"target_column": "active_power_source_2_phase_c"},
                    "metrics_39_value": {"target_column": "active_power_source_3_phase_a"},
                    "metrics_40_value": {"target_column": "active_power_source_3_phase_b"},
                    "metrics_41_value": {"target_column": "active_power_source_3_phase_c"},
                    "metrics_42_value": {"target_column": "active_power_source_4_phase_a"},
                    "metrics_43_value": {"target_column": "active_power_source_4_phase_b"},
                    "metrics_44_value": {"target_column": "active_power_source_4_phase_c"},
                    "metrics_45_value": {"target_column": "active_power_source_5_phase_a"},
                    "metrics_46_value": {"target_column": "active_power_source_5_phase_b"},
                    "metrics_47_value": {"target_column": "active_power_source_5_phase_c"},
                    "metrics_48_value": {"target_column": "active_power_source_6_phase_a"},
                    "metrics_49_value": {"target_column": "active_power_source_6_phase_b"},
                    "metrics_50_value": {"target_column": "active_power_source_6_phase_c"},
                    "metrics_58_value": {"target_column": "reactive_power_overall_phase_a"},
                    "metrics_59_value": {"target_column": "reactive_power_overall_phase_b"},
                    "metrics_60_value": {"target_column": "reactive_power_overall_phase_c"},
                    "metrics_85_value": {"target_column": "reactive_power_overall_average"},
                    "metrics_61_value": {"target_column": "reactive_power_source_1_phase_a"},
                    "metrics_62_value": {"target_column": "reactive_power_source_1_phase_b"},
                    "metrics_63_value": {"target_column": "reactive_power_source_1_phase_c"},
                    "metrics_64_value": {"target_column": "reactive_power_source_2_phase_a"},
                    "metrics_65_value": {"target_column": "reactive_power_source_2_phase_b"},
                    "metrics_66_value": {"target_column": "reactive_power_source_2_phase_c"},
                    "metrics_67_value": {"target_column": "reactive_power_source_3_phase_a"},
                    "metrics_68_value": {"target_column": "reactive_power_source_3_phase_b"},
                    "metrics_69_value": {"target_column": "reactive_power_source_3_phase_c"},
                    "metrics_70_value": {"target_column": "reactive_power_source_4_phase_a"},
                    "metrics_71_value": {"target_column": "reactive_power_source_4_phase_b"},
                    "metrics_72_value": {"target_column": "reactive_power_source_4_phase_c"},
                    "metrics_73_value": {"target_column": "reactive_power_source_5_phase_a"},
                    "metrics_74_value": {"target_column": "reactive_power_source_5_phase_b"},
                    "metrics_75_value": {"target_column": "reactive_power_source_5_phase_c"},
                    "metrics_76_value": {"target_column": "reactive_power_source_6_phase_a"},
                    "metrics_77_value": {"target_column": "reactive_power_source_6_phase_b"},
                    "metrics_78_value": {"target_column": "reactive_power_source_6_phase_c"},
                    "metrics_86_value": {"target_column": "apparent_power_overall_phase_a"},
                    "metrics_87_value": {"target_column": "apparent_power_overall_phase_b"},
                    "metrics_88_value": {"target_column": "apparent_power_overall_phase_c"},
                    "metrics_113_value": {"target_column": "apparent_power_overall_average"},
                    "metrics_89_value": {"target_column": "apparent_power_source_1_phase_a"},
                    "metrics_90_value": {"target_column": "apparent_power_source_1_phase_b"},
                    "metrics_91_value": {"target_column": "apparent_power_source_1_phase_c"},
                    "metrics_92_value": {"target_column": "apparent_power_source_2_phase_a"},
                    "metrics_93_value": {"target_column": "apparent_power_source_2_phase_b"},
                    "metrics_94_value": {"target_column": "apparent_power_source_2_phase_c"},
                    "metrics_95_value": {"target_column": "apparent_power_source_3_phase_a"},
                    "metrics_96_value": {"target_column": "apparent_power_source_3_phase_b"},
                    "metrics_97_value": {"target_column": "apparent_power_source_3_phase_c"},
                    "metrics_98_value": {"target_column": "apparent_power_source_4_phase_a"},
                    "metrics_99_value": {"target_column": "apparent_power_source_4_phase_b"},
                    "metrics_100_value": {"target_column": "apparent_power_source_4_phase_c"},
                    "metrics_101_value": {"target_column": "apparent_power_source_5_phase_a"},
                    "metrics_102_value": {"target_column": "apparent_power_source_5_phase_b"},
                    "metrics_103_value": {"target_column": "apparent_power_source_5_phase_c"},
                    "metrics_104_value": {"target_column": "apparent_power_source_6_phase_a"},
                    "metrics_105_value": {"target_column": "apparent_power_source_6_phase_b"},
                    "metrics_106_value": {"target_column": "apparent_power_source_6_phase_c"},
                    "metrics_114_value": {"target_column": "power_factor_overall_phase_a"},
                    "metrics_115_value": {"target_column": "power_factor_overall_phase_b"},
                    "metrics_116_value": {"target_column": "power_factor_overall_phase_c"},
                    "metrics_141_value": {"target_column": "power_factor_overall"},
                    "metrics_117_value": {"target_column": "power_factor_source_1_phase_a"},
                    "metrics_118_value": {"target_column": "power_factor_source_1_phase_b"},
                    "metrics_119_value": {"target_column": "power_factor_source_1_phase_c"},
                    "metrics_120_value": {"target_column": "power_factor_source_2_phase_a"},
                    "metrics_121_value": {"target_column": "power_factor_source_2_phase_b"},
                    "metrics_122_value": {"target_column": "power_factor_source_2_phase_c"},
                    "metrics_123_value": {"target_column": "power_factor_source_3_phase_a"},
                    "metrics_124_value": {"target_column": "power_factor_source_3_phase_b"},
                    "metrics_125_value": {"target_column": "power_factor_source_3_phase_c"},
                    "metrics_126_value": {"target_column": "power_factor_source_4_phase_a"},
                    "metrics_127_value": {"target_column": "power_factor_source_4_phase_b"},
                    "metrics_128_value": {"target_column": "power_factor_source_4_phase_c"},
                    "metrics_129_value": {"target_column": "power_factor_source_5_phase_a"},
                    "metrics_130_value": {"target_column": "power_factor_source_5_phase_b"},
                    "metrics_131_value": {"target_column": "power_factor_source_5_phase_c"},
                    "metrics_132_value": {"target_column": "power_factor_source_6_phase_a"},
                    "metrics_133_value": {"target_column": "power_factor_source_6_phase_b"},
                    "metrics_134_value": {"target_column": "power_factor_source_6_phase_c"},
                    "metrics_142_value": {"target_column": "frequency"},
                    "metrics_143_value": {"target_column": "import_active_energy_overall_phase_a"},
                    "metrics_144_value": {"target_column": "import_active_energy_overall_phase_b"},
                    "metrics_145_value": {"target_column": "import_active_energy_overall_phase_c"},
                    "metrics_170_value": {"target_column": "import_active_energy_overall_total"},
                    "metrics_146_value": {"target_column": "import_active_energy_source_1_phase_a"},
                    "metrics_147_value": {"target_column": "import_active_energy_source_1_phase_b"},
                    "metrics_148_value": {"target_column": "import_active_energy_source_1_phase_c"},
                    "metrics_149_value": {"target_column": "import_active_energy_source_2_phase_a"},
                    "metrics_150_value": {"target_column": "import_active_energy_source_2_phase_b"},
                    "metrics_151_value": {"target_column": "import_active_energy_source_2_phase_c"},
                    "metrics_152_value": {"target_column": "import_active_energy_source_3_phase_a"},
                    "metrics_153_value": {"target_column": "import_active_energy_source_3_phase_b"},
                    "metrics_154_value": {"target_column": "import_active_energy_source_3_phase_c"},
                    "metrics_155_value": {"target_column": "import_active_energy_source_4_phase_a"},
                    "metrics_156_value": {"target_column": "import_active_energy_source_4_phase_b"},
                    "metrics_157_value": {"target_column": "import_active_energy_source_4_phase_c"},
                    "metrics_158_value": {"target_column": "import_active_energy_source_5_phase_a"},
                    "metrics_159_value": {"target_column": "import_active_energy_source_5_phase_b"},
                    "metrics_160_value": {"target_column": "import_active_energy_source_5_phase_c"},
                    "metrics_161_value": {"target_column": "import_active_energy_source_6_phase_a"},
                    "metrics_162_value": {"target_column": "import_active_energy_source_6_phase_b"},
                    "metrics_163_value": {"target_column": "import_active_energy_source_6_phase_c"},
                    "metrics_171_value": {"target_column": "import_reactive_energy_overall_phase_a"},
                    "metrics_172_value": {"target_column": "import_reactive_energy_overall_phase_b"},
                    "metrics_173_value": {"target_column": "import_reactive_energy_overall_phase_c"},
                    "metrics_198_value": {"target_column": "import_reactive_energy_overall_total"},
                    "metrics_174_value": {"target_column": "import_reactive_energy_source_1_phase_a"},
                    "metrics_175_value": {"target_column": "import_reactive_energy_source_1_phase_b"},
                    "metrics_176_value": {"target_column": "import_reactive_energy_source_1_phase_c"},
                    "metrics_177_value": {"target_column": "import_reactive_energy_source_2_phase_a"},
                    "metrics_178_value": {"target_column": "import_reactive_energy_source_2_phase_b"},
                    "metrics_179_value": {"target_column": "import_reactive_energy_source_2_phase_c"},
                    "metrics_180_value": {"target_column": "import_reactive_energy_source_3_phase_a"},
                    "metrics_181_value": {"target_column": "import_reactive_energy_source_3_phase_b"},
                    "metrics_182_value": {"target_column": "import_reactive_energy_source_3_phase_c"},
                    "metrics_183_value": {"target_column": "import_reactive_energy_source_4_phase_a"},
                    "metrics_184_value": {"target_column": "import_reactive_energy_source_4_phase_b"},
                    "metrics_185_value": {"target_column": "import_reactive_energy_source_4_phase_c"},
                    "metrics_186_value": {"target_column": "import_reactive_energy_source_5_phase_a"},
                    "metrics_187_value": {"target_column": "import_reactive_energy_source_5_phase_b"},
                    "metrics_188_value": {"target_column": "import_reactive_energy_source_5_phase_c"},
                    "metrics_189_value": {"target_column": "import_reactive_energy_source_6_phase_a"},
                    "metrics_190_value": {"target_column": "import_reactive_energy_source_6_phase_b"},
                    "metrics_191_value": {"target_column": "import_reactive_energy_source_6_phase_c"},
                    "metrics_199_value": {"target_column": "apparent_energy_overall_phase_a"},
                    "metrics_200_value": {"target_column": "apparent_energy_overall_phase_b"},
                    "metrics_201_value": {"target_column": "apparent_energy_overall_phase_c"},
                    "metrics_226_value": {"target_column": "apparent_energy_overall_total"},
                    "metrics_202_value": {"target_column": "apparent_energy_source_1_phase_a"},
                    "metrics_203_value": {"target_column": "apparent_energy_source_1_phase_b"},
                    "metrics_204_value": {"target_column": "apparent_energy_source_1_phase_c"},
                    "metrics_205_value": {"target_column": "apparent_energy_source_2_phase_a"},
                    "metrics_206_value": {"target_column": "apparent_energy_source_2_phase_b"},
                    "metrics_207_value": {"target_column": "apparent_energy_source_2_phase_c"},
                    "metrics_208_value": {"target_column": "apparent_energy_source_3_phase_a"},
                    "metrics_209_value": {"target_column": "apparent_energy_source_3_phase_b"},
                    "metrics_210_value": {"target_column": "apparent_energy_source_3_phase_c"},
                    "metrics_211_value": {"target_column": "apparent_energy_source_4_phase_a"},
                    "metrics_212_value": {"target_column": "apparent_energy_source_4_phase_b"},
                    "metrics_213_value": {"target_column": "apparent_energy_source_4_phase_c"},
                    "metrics_214_value": {"target_column": "apparent_energy_source_5_phase_a"},
                    "metrics_215_value": {"target_column": "apparent_energy_source_5_phase_b"},
                    "metrics_216_value": {"target_column": "apparent_energy_source_5_phase_c"},
                    "metrics_217_value": {"target_column": "apparent_energy_source_6_phase_a"},
                    "metrics_218_value": {"target_column": "apparent_energy_source_6_phase_b"},
                    "metrics_219_value": {"target_column": "apparent_energy_source_6_phase_c"},
                    "metrics_227_value": {"target_column": "active_power_demand_overall_phase_a"},
                    "metrics_228_value": {"target_column": "active_power_demand_overall_phase_b"},
                    "metrics_229_value": {"target_column": "active_power_demand_overall_phase_c"},
                    "metrics_254_value": {"target_column": "active_power_demand_overall_total"},
                    "metrics_230_value": {"target_column": "active_power_demand_source_1_phase_a"},
                    "metrics_231_value": {"target_column": "active_power_demand_source_1_phase_b"},
                    "metrics_232_value": {"target_column": "active_power_demand_source_1_phase_c"},
                    "metrics_233_value": {"target_column": "active_power_demand_source_2_phase_a"},
                    "metrics_234_value": {"target_column": "active_power_demand_source_2_phase_b"},
                    "metrics_235_value": {"target_column": "active_power_demand_source_2_phase_c"},
                    "metrics_236_value": {"target_column": "active_power_demand_source_3_phase_a"},
                    "metrics_237_value": {"target_column": "active_power_demand_source_3_phase_b"},
                    "metrics_238_value": {"target_column": "active_power_demand_source_3_phase_c"},
                    "metrics_239_value": {"target_column": "active_power_demand_source_4_phase_a"},
                    "metrics_240_value": {"target_column": "active_power_demand_source_4_phase_b"},
                    "metrics_241_value": {"target_column": "active_power_demand_source_4_phase_c"},
                    "metrics_242_value": {"target_column": "active_power_demand_source_5_phase_a"},
                    "metrics_243_value": {"target_column": "active_power_demand_source_5_phase_b"},
                    "metrics_244_value": {"target_column": "active_power_demand_source_5_phase_c"},
                    "metrics_245_value": {"target_column": "active_power_demand_source_6_phase_a"},
                    "metrics_246_value": {"target_column": "active_power_demand_source_6_phase_b"},
                    "metrics_247_value": {"target_column": "active_power_demand_source_6_phase_c"},
                    "metrics_255_value": {"target_column": "reactive_power_demand_overall_phase_a"},
                    "metrics_256_value": {"target_column": "reactive_power_demand_overall_phase_b"},
                    "metrics_257_value": {"target_column": "reactive_power_demand_overall_phase_c"},
                    "metrics_282_value": {"target_column": "reactive_power_demand_overall_total"},
                    "metrics_258_value": {"target_column": "reactive_power_demand_source_1_phase_a"},
                    "metrics_259_value": {"target_column": "reactive_power_demand_source_1_phase_b"},
                    "metrics_260_value": {"target_column": "reactive_power_demand_source_1_phase_c"},
                    "metrics_261_value": {"target_column": "reactive_power_demand_source_2_phase_a"},
                    "metrics_262_value": {"target_column": "reactive_power_demand_source_2_phase_b"},
                    "metrics_263_value": {"target_column": "reactive_power_demand_source_2_phase_c"},
                    "metrics_264_value": {"target_column": "reactive_power_demand_source_3_phase_a"},
                    "metrics_265_value": {"target_column": "reactive_power_demand_source_3_phase_b"},
                    "metrics_266_value": {"target_column": "reactive_power_demand_source_3_phase_c"},
                    "metrics_267_value": {"target_column": "reactive_power_demand_source_4_phase_a"},
                    "metrics_268_value": {"target_column": "reactive_power_demand_source_4_phase_b"},
                    "metrics_269_value": {"target_column": "reactive_power_demand_source_4_phase_c"},
                    "metrics_270_value": {"target_column": "reactive_power_demand_source_5_phase_a"},
                    "metrics_271_value": {"target_column": "reactive_power_demand_source_5_phase_b"},
                    "metrics_272_value": {"target_column": "reactive_power_demand_source_5_phase_c"},
                    "metrics_273_value": {"target_column": "reactive_power_demand_source_6_phase_a"},
                    "metrics_274_value": {"target_column": "reactive_power_demand_source_6_phase_b"},
                    "metrics_275_value": {"target_column": "reactive_power_demand_source_6_phase_c"},
                    "metrics_283_value": {"target_column": "apparent_power_demand_overall_phase_a"},
                    "metrics_284_value": {"target_column": "apparent_power_demand_overall_phase_b"},
                    "metrics_285_value": {"target_column": "apparent_power_demand_overall_phase_c"},
                    "metrics_310_value": {"target_column": "apparent_power_demand_overall_total"},
                    "metrics_286_value": {"target_column": "apparent_power_demand_source_1_phase_a"},
                    "metrics_287_value": {"target_column": "apparent_power_demand_source_1_phase_b"},
                    "metrics_288_value": {"target_column": "apparent_power_demand_source_1_phase_c"},
                    "metrics_289_value": {"target_column": "apparent_power_demand_source_2_phase_a"},
                    "metrics_290_value": {"target_column": "apparent_power_demand_source_2_phase_b"},
                    "metrics_291_value": {"target_column": "apparent_power_demand_source_2_phase_c"},
                    "metrics_292_value": {"target_column": "apparent_power_demand_source_3_phase_a"},
                    "metrics_293_value": {"target_column": "apparent_power_demand_source_3_phase_b"},
                    "metrics_294_value": {"target_column": "apparent_power_demand_source_3_phase_c"},
                    "metrics_295_value": {"target_column": "apparent_power_demand_source_4_phase_a"},
                    "metrics_296_value": {"target_column": "apparent_power_demand_source_4_phase_b"},
                    "metrics_297_value": {"target_column": "apparent_power_demand_source_4_phase_c"},
                    "metrics_298_value": {"target_column": "apparent_power_demand_source_5_phase_a"},
                    "metrics_299_value": {"target_column": "apparent_power_demand_source_5_phase_b"},
                    "metrics_300_value": {"target_column": "apparent_power_demand_source_5_phase_c"},
                    "metrics_301_value": {"target_column": "apparent_power_demand_source_6_phase_a"},
                    "metrics_302_value": {"target_column": "apparent_power_demand_source_6_phase_b"},
                    "metrics_303_value": {"target_column": "apparent_power_demand_source_6_phase_c"},
                    "metrics_311_value": {"target_column": "current_demand_overall_phase_a"},
                    "metrics_312_value": {"target_column": "current_demand_overall_phase_b"},
                    "metrics_313_value": {"target_column": "current_demand_overall_phase_c"},
                    "metrics_314_value": {"target_column": "current_demand_source_1_phase_a"},
                    "metrics_315_value": {"target_column": "current_demand_source_1_phase_b"},
                    "metrics_316_value": {"target_column": "current_demand_source_1_phase_c"},
                    "metrics_317_value": {"target_column": "current_demand_source_2_phase_a"},
                    "metrics_318_value": {"target_column": "current_demand_source_2_phase_b"},
                    "metrics_319_value": {"target_column": "current_demand_source_2_phase_c"},
                    "metrics_320_value": {"target_column": "current_demand_source_3_phase_a"},
                    "metrics_321_value": {"target_column": "current_demand_source_3_phase_b"},
                    "metrics_322_value": {"target_column": "current_demand_source_3_phase_c"},
                    "metrics_323_value": {"target_column": "current_demand_source_4_phase_a"},
                    "metrics_324_value": {"target_column": "current_demand_source_4_phase_b"},
                    "metrics_325_value": {"target_column": "current_demand_source_4_phase_c"},
                    "metrics_326_value": {"target_column": "current_demand_source_5_phase_a"},
                    "metrics_327_value": {"target_column": "current_demand_source_5_phase_b"},
                    "metrics_328_value": {"target_column": "current_demand_source_5_phase_c"},
                    "metrics_329_value": {"target_column": "current_demand_source_6_phase_a"},
                    "metrics_330_value": {"target_column": "current_demand_source_6_phase_b"},
                    "metrics_331_value": {"target_column": "current_demand_source_6_phase_c"},
                    "metrics_332_value": {"target_column": "voltage_unbalance_factor"},
                    "metrics_339_value": {"target_column": "current_unbalance_factor"},
                    "metrics_340_value": {"target_column": "voltage_crest_factor_overall_phase_a"},
                    "metrics_341_value": {"target_column": "voltage_crest_factor_overall_phase_b"},
                    "metrics_342_value": {"target_column": "voltage_crest_factor_overall_phase_c"},
                    "metrics_343_value": {"target_column": "di_counter_channel_1"},
                    "metrics_344_value": {"target_column": "di_counter_channel_2"},
                    "metrics_345_value": {"target_column": "di_counter_channel_3"},
                    "metrics_346_value": {"target_column": "di_counter_channel_4"},
                    "metrics_347_value": {"target_column": "di_counter_channel_5"},
                    "metrics_348_value": {"target_column": "di_counter_channel_6"},
                    "metrics_349_value": {"target_column": "di_counter_channel_7"},
                    "metrics_350_value": {"target_column": "di_counter_channel_8"},
                    "metrics_351_value": {"target_column": "di_counter_channel_9"},
                    "metrics_352_value": {"target_column": "di_counter_channel_10"},
                    "metrics_353_value": {"target_column": "di_counter_channel_11"},
                    "metrics_354_value": {"target_column": "di_counter_channel_12"},
                    "metrics_355_value": {"target_column": "di_counter_channel_13"},
                    "metrics_356_value": {"target_column": "di_counter_channel_14"},
                    "metrics_357_value": {"target_column": "di_counter_channel_15"},
                    "metrics_358_value": {"target_column": "di_counter_channel_16"},
                    "metrics_359_value": {"target_column": "di_counter_channel_17"},
                    "metrics_360_value": {"target_column": "di_counter_channel_18"},
                },
            },
        },
    },
}
